Trying some stuff with 2fontface

diff --git a/utils/2fontface b/utils/2fontface
--- a/utils/2fontface
+++ b/utils/2fontface
@@ -1,8 +1,78 @@
 #!/bin/env bash
 
-# set -xe
 
-declare -A groups
+VERBOSE=0
+DRY_RUN=0
+
+while [[ $# -gt 2 ]]; do
+    case "$1" in
+	--verbose|-v)
+	    VERBOSE=1
+	    ;;
+	--dry-run|-n)
+	    DRY_RUN=1
+	    ;;
+    esac
+
+    shift
+done
+
+TARGET="$1"
+OUTPUT="$2"
+
+
+
+is_assoc() {
+    local decl
+    
+    decl=$(declare -p "$1" 2>/dev/null) || return 1
+
+    [[ "$decl" == "declare -A"* ]]
+}
+
+
+is_array() {
+    local decl
+    
+    decl=$(declare -p "$1" 2>/dev/null) || return 1
+
+    [[ "$decl" == "declare -a"* ]]
+}
+
+
+find_fonts() {
+    local root="$1"
+    fonts=()
+
+    if [[ ! -e "$root" ]]; then
+	echo "error: $root: No such file or directory"
+	return
+    fi
+    
+    local cmd=(
+	find
+	"$root"
+	-type f
+	-regextype posix-extended
+	-iregex '.*\.(woff2|woff|otf"ttf")$'
+	-print0
+    )
+
+    mapfile -d '' fonts < <("${cmd[@]}")
+
+    if [[ "${#fonts[@]}" -lt 1 ]]; then
+	log_err "could not find any fonts in this directory"
+	return
+    fi
+	   
+    return
+}
+
+parse_font() {
+    local font="$1"
+
+    echo "$font"
+}
 
 parse_variant() {
     local variant="$1"
@@ -21,6 +91,9 @@ parse_variant() {
 	    style=oblique
 	    variant=${variant%Oblique}
 	    ;;
+	*Text)
+	    style=text
+	    variant=${variant%Text}
     esac
 
     case "$variant" in
@@ -61,6 +134,9 @@ parse_variant() {
 	book)
 	    weight=350
 	    ;;
+	text)
+	    weight=450
+	    ;;
 	medium)
 	    weight=500
 	    ;;
@@ -83,32 +159,19 @@ parse_variant() {
     fi
 }
 
-log() {
+info() {
     if (( VERBOSE )); then
 	echo "$1" >&2
     fi
 }
 
-TARGET="$1"
-OUTPUT="$2"
-VERBOSE=0
-DRY_RUN=0
 
-# while [[ $# -gt 0 ]]; do
-#     case "$1" in
-# 	--verbose|-v)
-# 	    VERBOSE=1
-# 	    ;;
-# 	--dry-run|-n)
-# 	    DRY_RUN=1
-# 	    ;;
-# 	*)
-# 	    TARGET="$1"
-# 	    ;;
-#     esac
+log_err() {
+    local script="${BASH_SOURCE[0]##*/}"
+    local line_num="${BASH_LINENO[0]}"
+    echo "${script}:${line_num}: $*" >&2
+}
 
-#     shift
-# done
 
 if (( DRY_RUN )); then
     exec 3>&1
@@ -117,147 +180,185 @@ else
 fi
 
 
-if [[ ! -d "$TARGET" ]]; then
+if [[ ! -e "$TARGET" ]]; then
 	echo "Dir not found"
 	exit 1
 fi
 
+declare -A groups
+
 font_count=0
 family_count=0
 
-for filename in "$TARGET"/*.{ttf,otf,woff,woff2}; do
-    [ -e "$filename" ] || continue
 
-    path="$filename"
-    filename=$(basename -- "$path")
-    
-    base="${filename%.*}"
-    variant="${base##*-}"
-    family="${base%-*}"
-    format="${filename##*.}"
+info ""
+info "+ FIND FONTS"
 
-    if [[ "$family" == "$base" ]]; then
-	family="$base"
-	variant="Regular"
-    fi
+fonts_dir="$TARGET"
 
-    style_source="$variant"
-
-    parse_variant "$variant"
-
-    case "${format,,}" in
-	woff2)
-	    priority=1
-	    css_format="woff2"
-	    ;;
-	woff)
-	    priority=2
-	    css_format="woff"
-	    ;;
-	ttf)
-	    priority=3
-	    css_format="truetype"
-	    ;;
-	otf)
-	    priority=4
-	    css_format="opentype"
-	    ;;
-    esac
-
-    style_priority=0
-	
-    case "$style_source" in
-	*Italic)
-	    style_priority=1
-	    ;;
-	*Oblique)
-	    style_priority=2
-	    ;;
-    esac
-    
-    log "  $filename"
-    log "    family: $family"
-    log "    weight: $weight"
-    log "    style:  $style"
-    log "    style priority: $style_priority"
-    log "    stretch: $stretch"
-
-    key="${family}|${weight}|${style}|${stretch}"
-    src="url('/static/fonts/$filename') format('$css_format')"
-
-    record="${priority}|${style_priority}|${src}|${filename}"
-    groups["$key"]+="$record"$'\n'
-
-    ((font_count++))
-done
-
-family_count=$(printf "%s\n" "${!groups[@]}" | cut -d'|' -f1 | sort -u | wc -l)
-
-while IFS= read -r family; do
-    count=$(printf "%s\n" "${!groups[@]}" | grep "^${family}|" | wc -l)
-
-done < <(
-    printf "%s\n" "${!groups[@]}" |
-	cut -d'|' -f1 |
-	sort -u
-)
-
-{
-    echo "/*"
-    echo " * This file was generated by 2fontface."
-    echo " */"
-    echo
-} >&3
-
-for key in $(printf "%s\n" "${!groups[@]}" | sort); do
-    IFS='|' read -r family weight style stretch <<< "$key"
-    
-    {
-	echo "@font-face {"
-	echo "    font-family: '${family}';"
-	echo "    src:"
-
-	mapfile -t lines < <(
-	    printf "%s" "${groups[$key]}" |
-		sort -t'|' -k1,1n -k2,2n -k3,3
-	)
-
-	for ((i=0; i<${#lines[@]}; i++)); do
-	    IFS='|' read -r _ _ src filename <<< "${lines[$i]}"
-	    
-	    if (( i == ${#lines[@]} - 1 )); then
-		echo "        $src;"
-	    else
-		echo "        $src,"
-	    fi
-	done
-
-	echo "    font-weight: ${weight};"
-	echo "    font-style: ${style};"
-
-	if [[ "$stretch" != "normal" ]]; then
-	    echo "    font-stretch: ${stretch};"
-	fi
-	
-	echo "    font-display: swap;"
-	echo "}"
-	echo
-    } >&3
-done
-
-exec 3>&-
-
-{
-    echo
-    echo "Generated: $OUTPUT"
-    
-    echo "Families:  $family_count"
-    for family in $(printf "%s\n" "${!groups[@]}" | cut -d'|' -f 1 | sort -u); do
-	count=$(printf "%s\n" "${!groups[@]}" | grep "^${family}|" | wc -l)
-	echo "  $family ($count faces)"
+if ! find_fonts "$fonts_dir"; then
+    echo "could not find any fonts in this directory"
+else
+    for font in "${fonts[@]}"; do
+	parse_font "$font"
     done
+fi
 
-    echo "Faces:     ${#groups[@]}"
-    echo "Files:     $font_count"
-} >&2
+# for filename in "$TARGET"/*.{woff,woff2}; do
+#     [ -e "$filename" ] || continue
+
+#     path="$filename"
+#     filename=$(basename -- "$path")
+    
+#     base="${filename%.*}"
+#     variant="${base##*-}"
+#     family="${base%-*}"
+#     format="${filename##*.}"
+
+#     if [[ "$family" == "$base" ]]; then
+# 	family="$base"
+# 	variant="Regular"
+#     fi
+
+#     style_source="$variant"
+
+    
+#     parse_variant "$variant"
+
+
+#     case "${format,,}" in
+# 	woff2)
+# 	    priority=1
+# 	    css_format="woff2"
+# 	    ;;
+# 	woff)
+# 	    priority=2
+# 	    css_format="woff"
+# 	    ;;
+# 	ttf)
+# 	    priority=3
+# 	    css_format="truetype"
+# 	    ;;
+# 	otf)
+# 	    priority=4
+# 	    css_format="opentype"
+# 	    ;;
+#     esac
+
+
+#     render_priority=0
+#     style_priority=0
+
+#     case "$style_source" in
+# 	*Regular|*Text|*Book|*Roman)
+# 	    render_priority=1
+# 	    style_priority=1
+# 	    ;;
+# 	*Italic)
+# 	    render_priority=2
+# 	    style_priority=2
+# 	    ;;
+# 	*)
+# 	    render_priority=3;
+# 	    style_priority=3
+# 	    ;;
+#     esac
+
+      
+#     key="${render_priority}|${family}|${weight}|${style}|${stretch}"
+
+#     src="url('/static/fonts/$filename') format('$css_format')"
+#     record="${priority}|${style_priority}|${src}|${filename}"
+
+#     groups["$key"]+="$record"$'\n'
+
+#     ((font_count++))
+
+#     log "| + FONT"
+#     log "| | - file: ($filename)"
+#     log "| | - family: ($family)"
+#     log "| | - style: ($style) weight: ($weight) stretch: ($stretch) variable: ($variable)"
+#     log "| | - css_format: ($css_format) format_priority: ($priority)"
+#     log "| | - style_source: ($style_source)"
+#     log "| | - render_priority: ($render_priority) style_priority: ($style_priority)"
+# done
+
+
+# family_count=$(printf "%s\n" "${!groups[@]}" | cut -d'|' -f2 | sort -u | wc -l)
+# group_keys=$(printf "%s\n" "${!groups[@]}" | cut -d'|' -f2 | sort -u)
+
+
+# log "+ COUNT"
+# log "| + family count ($family_count):"
+
+# while IFS= read -r family; do
+#     count_faces=$(printf "%s\n" "${!groups[@]}" | grep "${family}|" | wc -l)
+
+#     log "| | - $family ($count_faces faces)"
+# done < <(printf "%s\n" "${!groups[@]}" | cut -d'|' -f2 | sort -u)
+
+
+# log "+ GENERATE"
+# keys=$(printf "%s\n" "${!groups[@]}")
+
+# {
+#     echo "/*"
+#     echo " * This file was generated by 2fontface."
+#     echo " */"
+#     echo
+# } >&3
+
+# for key in $(printf "%s\n" "${!groups[@]}" | sort -u); do
+#     log "| - generating $key"
+
+#     IFS='|' read -r _ family weight style stretch <<< "$key"
+    
+#     {
+# 	echo "@font-face {"
+# 	echo "    font-family: '${family}';"
+# 	echo "    src:"
+
+# 	mapfile -t lines < <(
+# 	    printf "%s" "${groups[$key]}" |
+# 		sort -t'|' -k1,1n -k2,2n -k3,3
+# 	)
+
+# 	for ((i=0; i<${#lines[@]}; i++)); do
+# 	    IFS='|' read -r _ _ src filename <<< "${lines[$i]}"
+	    
+# 	    if (( i == ${#lines[@]} - 1 )); then
+# 		echo "        $src;"
+# 	    else
+# 		echo "        $src,"
+# 	    fi
+# 	done
+
+# 	echo "    font-weight: ${weight};"
+# 	echo "    font-style: ${style};"
+
+# 	if [[ "$stretch" != "normal" ]]; then
+# 	    echo "    font-stretch: ${stretch};"
+# 	fi
+	
+# 	echo "    font-display: swap;"
+# 	echo "}"
+# 	echo
+#     } >&3
+# done
+
+# exec 3>&-
+
+# {
+#     echo
+#     echo "Generated: $OUTPUT"
+    
+#     echo "Families:  $family_count"
+#     for family in $(printf "%s\n" "${!groups[@]}" | cut -d'|' -f 2 | sort -u); do
+# 	count=$(printf "%s\n" "${!groups[@]}" | grep "${family}|" | wc -l)
+# 	echo "  $family ($count faces)"
+#     done
+
+#     echo "Faces:     ${#groups[@]}"
+#     echo "Files:     $font_count"
+# } >&2
 
